import PortfolioClient from "@/components/portfolio-client";

export type Project = { name: string; account: "vonssy" | "REY-STTP"; description: string; category: string[]; tags: string[]; repo: string; demo?: string; signal: string; details: { overview: string; approach: string; decisions: string; challenges: string } };

export const projects: Project[] = [
  { name: "Dawn-BOT", account: "vonssy", description: "A Dawn Validator manager built around token setup, account handling, proxy rotation, keep-alive pings, and concurrent execution.", category: ["Automation", "Bots"], tags: ["Python", "Multithreading", "Proxies"], repo: "https://github.com/vonssy/Dawn-BOT", demo: "https://t.me/vonssy_part_2", signal: "111 stars · 18 forks", details: { overview: "Automated Dawn Validator management with multi-threading and proxy support.", approach: "The repository separates token setup from runtime execution, stores account and proxy inputs in simple files, and exposes proxy mode and rotation choices at startup.", decisions: "The README calls out automatic bearer-token extraction, account retrieval, invalid-proxy rotation, ping signals, and multi-account threading.", challenges: "The documented runtime is shaped around real service conditions: captcha setup, proxy reliability, and keeping several accounts alive." } },
  { name: "PharosTestnet-BOT", account: "vonssy", description: "Multi-account Web3 automation for Pharos Atlantic Testnet: check-ins, faucet claims, transfers, and proxy-aware execution.", category: ["Web3", "Blockchain", "Bots"], tags: ["Python", "web3.py", "EVM"], repo: "https://github.com/vonssy/PharosTestnet-BOT", demo: "https://t.me/vonssy_part_2", signal: "127 stars · 41 forks", details: { overview: "Automated Web3 interaction for Pharos Atlantic Testnet.", approach: "Accounts are supplied as private keys, while the bot runs repeatable network actions across multiple accounts through web3, eth-account, ABI, and utility packages.", decisions: "Proxy support and invalid-proxy rotation are first-class runtime choices, alongside daily check-in, faucet, and transfer actions.", challenges: "The README reflects the operational edge cases of wallet automation: account lists, network libraries, proxies, and repeated actions." } },
  { name: "KiteAi-BOT", account: "vonssy", description: "A configurable on-chain operations bot spanning staking, rewards, quizzes, AI-agent interactions, multisig wallets, swaps, and bridges.", category: ["Web3", "Automation", "Bots"], tags: ["Python", "web3.py", "Multisig"], repo: "https://github.com/vonssy/KiteAi-BOT", demo: "https://t.me/vonssy_part_2", signal: "83 stars · 27 forks", details: { overview: "Automated Kite AI network operations across multiple accounts.", approach: "Feature flags in .env control the workflow: faucet, deposits, withdrawals, staking, rewards, quiz completion, agent chat, swaps, and bridges.", decisions: "The project makes network actions configurable rather than forcing one fixed sequence, while keeping proxy rotation and account management explicit.", challenges: "The documented surface area spans several transaction types, captcha configuration, proxy handling, and multi-account state." } },
  { name: "HahaWallet-BOT", account: "vonssy", description: "Multi-account automation for daily karma claims and quest completion with optional proxy support and rotation.", category: ["Automation", "Bots"], tags: ["Python", "Accounts", "Proxies"], repo: "https://github.com/vonssy/HahaWallet-BOT", demo: "https://t.me/vonssy_part_2", signal: "70 stars · 16 forks", details: { overview: "Automated claim and quest workflows for Haha Wallet.", approach: "The bot reads account records from JSON, accepts an optional proxy list, and exposes a small interactive runtime for proxy mode and rotation.", decisions: "Credential structure, proxy handling, and daily actions are kept close to the configuration surface so the workflow is easy to run repeatedly.", challenges: "The README centers the practical constraints: multiple account credentials, invalid proxies, and repeatable daily tasks." } },
  { name: "Vonssy-AI", account: "REY-STTP", description: "A multi-provider AI chatbot with streamed responses, persistent sessions, OAuth, quotas, and provider fallback.", category: ["Web", "Tools", "AI / ML"], tags: ["Next.js 16", "TypeScript", "PostgreSQL"], repo: "https://github.com/REY-STTP/Vonssy-AI", demo: "https://vonssy-ai.vercel.app", signal: "Current full-stack build", details: { overview: "A unified interface for multiple AI gateways and models.", approach: "The application combines a Next.js App Router frontend with PostgreSQL, Drizzle, Auth.js, streamed SSE responses, and a provider registry.", decisions: "The README documents server-side session revalidation, HMAC identity hashing, a three-layer quota system, cursor pagination, and a fallback gateway for 429 responses.", challenges: "The system has to coordinate streaming, persistence, authentication, rate limits, provider differences, and responsive chat UX." } },
  { name: "Kusoparse", account: "REY-STTP", description: "A responsive parser that extracts Kusonime metadata, resolves shortlinks, and returns direct download links from validated URLs.", category: ["Web", "Scraping", "Tools"], tags: ["Next.js", "TypeScript", "Framer Motion"], repo: "https://github.com/REY-STTP/Kusoparse", demo: "https://kusoparse.vercel.app", signal: "Live web tool", details: { overview: "A lightweight web interface for parsing Kusonime pages.", approach: "The tool validates Kusonime URLs, extracts anime metadata, and resolves documented shortlink providers into a cleaner download flow.", decisions: "The README explicitly positions responsiveness, strict URL validation, and a focused single-purpose interface as core features.", challenges: "The project deals with inconsistent external pages, shortlink/ad-locker resolution, and keeping the interaction simple for the visitor." } },
  { name: "Facial Expression Detection App", account: "REY-STTP", description: "An earlier AI and backend project using Face++ to classify uploaded images into seven expression categories.", category: ["AI / ML", "Web"], tags: ["Node.js", "Express", "MongoDB"], repo: "https://github.com/REY-STTP/Facial-Expression-Detection-App", signal: "Earlier experiment", details: { overview: "A Face++-integrated image analysis application.", approach: "The backend accepts image uploads, sends them to Face++, and stores or serves image-analysis records through a MongoDB-backed API.", decisions: "The README documents JWT authentication, bcrypt password hashing, validation, Multer uploads, and CRUD image endpoints.", challenges: "The project combines external AI API calls with user auth, file handling, data persistence, and API access control." } },
];

const philosophy = [
  ["Build for reality", "Software should meet real APIs, networks, wallets, services, and failure conditions."],
  ["Automate the boring parts", "Repeated workflows become useful when they can run predictably without supervision."],
  ["Reliability matters", "Retries, rate limits, proxies, state, concurrency, and recovery deserve deliberate handling."],
  ["Keep it practical", "Prefer understandable systems over abstractions that make the work harder to operate."],
];

const stack = [
  ["Languages", "Python · JavaScript · TypeScript · PHP · C · C++ · SQL · Dart"],
  ["Web", "Next.js · React · Node.js · Express · Tailwind CSS"],
  ["Automation", "Multi-account flows · browser automation · scraping · APIs · concurrency · proxy systems"],
  ["Web3", "EVM wallets · web3.py · RPC/API interaction · staking · swaps · bridges · testnets"],
];

export default function Home() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "Reyvaldi Zakaria",
    alternateName: "Vonssy",
    url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://github.com/vonssy",
    image: "https://avatars.githubusercontent.com/u/86215416?v=4",
    jobTitle: "Web3 Builder and Automation Engineer",
    sameAs: ["https://github.com/vonssy", "https://github.com/REY-STTP", "https://t.me/vonssy_part_2"],
    knowsAbout: ["Web3", "Python automation", "Blockchain automation", "Web scraping", "Backend engineering"],
  };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, "\\u003c") }} /><PortfolioClient projects={projects} philosophy={philosophy} stack={stack} /></>;
}
